### PR TITLE
added setlistFM api and got search from artist input to return setlis…

### PR DESCRIPTION
**Pull request by laylajooya**
…t array

### CODE REVIEW

**Comment by laylajooya** [comment]
used https://gist.github.com/deanius/d7bec0d437bb76bf5f43d1b0fd01799a to resolve below
Screen Shot 2019-04-18 at 9 40 10 AM

**Comment by laylajooya** [comment]
closes #11

**Review by aekoh — COMMENTED** [review]
1. I was able to review the added setlistFM api 
2. I was able to see the artist input return the setlist information.

**Review by aekoh — APPROVED** [review]
1. I was able to review the added setlistFM api
2. I was able to see the artist input return the setlistFM information

**Pull request merged**
